### PR TITLE
Copies statics from the Wrapped component to the Injected component

### PR DESCRIPTION
**Pull request by Sparragus**
## Description
Copies static values set on the Wrapped component over to the Injected component.

Here are two examples where this is done: [`react-router`](https://github.com/ReactTraining/react-router/blob/469fc9f7f0077fd8c1d794ab93d519adbfa851ea/packages/react-router/modules/withRouter.js#L25) and [`react-redux`](https://github.com/reactjs/react-redux/blob/ea53d6fb076359a864a1d543568d951d4b3eab3d/src/components/connect.js#L365).

### CODE REVIEW

**Comment by Sparragus** [comment]
I know this is the third PR with this feature (see https://github.com/yahoo/react-intl/pull/433 and https://github.com/yahoo/react-intl/pull/1064), but the other PRs have been either forgotten or some check did not pass.

I seriously hope to see this PR become merged. Without it, devs need to make dirty workarounds to copy static values.

**Comment by ArmandoAssuncao** [comment]
this could be merged.

**Comment by infiman** [comment]
Having `preload` static method in my components for my SSR implementation, but `injectIntl` is not hoisting it after wrapping them. Any chance this PR will be merged? Thanks in advance!

**Comment by kyusu** [comment]
This would be very helpful indeed!

**Comment by ericketts** [comment]
I've had to create a wrapper for `injectIntl` that does a call to `hoistNonReactStatic`... this should certainly be merged

**Comment by adrienharnay** [comment]
Yes please

**Comment by StorytellerCZ** [comment]
My branch has it merged (together with other PRs) if you really need this: https://github.com/Freedombase/react-intl

**Comment by redonkulus** [comment]
@okuryu do you want to review and merge?

**Comment by hank7444** [comment]
Why it still not be merged??

**Comment by kelly-tock** [comment]
What is the alternative workaround if this is not merged?

**Comment by ericketts** [comment]
@kelly-tock I've defined a file in my project, called `injectIntl.js` (some of this may not apply to you if you're not a flow user):

```javascript
import * as React from 'react';
import {injectIntl as baseInjectIntl, type IntlShape} from 'react-intl';
import hoistNonReactStatic from 'hoist-non-react-statics';

type TOpts = {intlPropName: string, withRef: boolean};

export default function injectIntl<Props, SanitizedProps: $Diff<Props, {intl: IntlShape}>>(
  BaseComponent: React.ComponentType<Props>,
  options?: TOpts
): React.ComponentType<SanitizedProps> {
  const WrappedComponent = baseInjectIntl(BaseComponent, options);
  hoistNonReactStatic(WrappedComponent, BaseComponent);
  return WrappedComponent;
}

export type {IntlShape} from 'react-intl';
```

so you just import that with `import injectIntl, {type IntlShape} from 'utils/injectIntl`, and use it how you'd use the built in fn.

**Comment by redonkulus** [comment]
Closed via https://github.com/yahoo/react-intl/pull/1141

**Pull request closed without merging**
