### PR TITLE
Hoist statics in injectIntl

### PR DESCRIPTION
**Pull request by ArnoSaine**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by deecewan** [comment]
@ArnoSaine can you please sign the CLA? alternatively, I'm happy to submit this PR.

**Comment by ghostd** [comment]
Duplicate of #433 ?

**Comment by ArnoSaine** [comment]
@deecewan I've signed the CLA. 
image

**Comment by ArnoSaine** [comment]
@ghostd Definitely. How I didn't see it :astonished:

**Comment by StorytellerCZ** [comment]
Superseded by #1073

**Comment by infiman** [comment]
Having `preload` static method in my components for my SSR implementation, but `injectIntl` is not hoisting it after wrapping them. Any chance this PR or #433 or #1073 will be merged? Thanks in advance!

**Comment by redonkulus** [comment]
Closing as duplicate of https://github.com/yahoo/react-intl/pull/1073

**Pull request closed without merging**
