### PR TITLE
Comment typo fix. processional --> professional

### PR DESCRIPTION
**Pull request by TimelyToga**
Hardly anything earth-shattering :)

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by okuryu** [comment]
Thanks for your PR! Could you sign the CLA?

**Comment by TimelyToga** [comment]
Sorry for the multi-month lag! I have just signed the CLA.

**Comment by okuryu** [comment]
Hmm, @yahoocla seems not to works fine..

**Comment by okuryu** [comment]
@TimelyToga Could you attach a screenshot of https://yahoocla.herokuapp.com/ ?

**Comment by TimelyToga** [comment]
image

**Comment by TimelyToga** [comment]
image

**Pull request merged**
