### PR TITLE
Added french local

### PR DESCRIPTION
**Pull request by CarlBosch**
extended the translation sample to include a real foreign language (french)

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by CarlBosch** [comment]
agreed on Yahoo CLA

**Comment by ericf** [comment]
@CarlBosch thanks for offering this, but this isn't how the example is suppose to work. The idea is that you only put the default language strings in the source code and the tooling takes care of the rest. For this example to _simulate_ translation, I have a automated script which transforms to upper case.

**Comment by CarlBosch** [comment]
Hi,
I'm quite new to react-intl so please don't mind me asking, was what I proposed a reasonable way to do translation in other languages? Or is there another (better) way to achieve this? 
Thanks,
Carl

**Comment by ericf** [comment]
`defaultMessage` is for defining the default message for the default language. There's `babel-plugin-react-intl` that will do the extraction into a JSON file so that they strings can be provided to a translator.

After having the strings translated, they can then be passed-in at runtime via `<IntlProvider messages={traslatedStringsCollection}>`.

**Pull request closed without merging**
