### PR TITLE
Add React Router example

### PR DESCRIPTION
**Pull request by ericf**

### CODE REVIEW

**Comment by baer** [comment]
This is a great example! Thanks for writing this. I haven't had time to do the 1.x analysis but when I do I'll see if I can either make a PR with an example or just a comment in the docs.

**Comment by ericf** [comment]
@baer cool, sounds good!

**Comment by anomaly44** [comment]
@baer can you provide more info, I m having the same problem using SSR, but I'm clueless on where to look. Thanks in advance.

**Comment by MasonChinkin** [comment]
> @baer can you provide more info, I m having the same problem using SSR, but I'm clueless on where to look. Thanks in advance.

@anomaly44 I'm having the same problem as you 3 years in the future after upgrading to React 16 SSR. Did you recommend any material?

**Comment by anomaly44** [comment]
@MasonChinkin I can't remember what it was exactly. But make sure to load the correct locale en make sure all needed props are there on the server. Havent used a custom SSR method anymore in the last couple of years. So that's all I can say at the moment.

**Comment by MasonChinkin** [comment]
@anomaly44 thanks. Turned out that while the error message was pointing to intl and react-router, the problem was actually a version of react-transition-group incompatible with react 16. Fun stuff...

**Pull request merged**
