### PR TITLE
Fix locale data and upgrade intl-* dependencies

### LINKED ISSUE #78: About locale 'zh-Hant-TW'
Hi, is there locale ```zh-Hant-TW``` that I can use, or need to add it manually?
Thanks for answering.

### PR DESCRIPTION
**Pull request by ericf**
## Fixed Locale Data

This vastly improves the locale data in the following ways:

* Added locale data for all leaf locales which differ from their root locale's data; e.g. "zh-Hant-TW" is not the same as "zh".

* Properly de-duplicate data for all CLDR locales by correctly traversing a locale's hierarchy of ancestor locales.

* Added data for the following languages:
  aa, agq, bas, bh, ckb, dav, dje, dsb, dua, dv, dyo, ebu, ewo, guw, guz, hsb, ia, in, iu, iw, jbo, ji, jv, jw, kaj, kam, kcg, khq, ki, kln, kok, ksf, ku, lb, lu, luo, luy, mer, mfe, mgh, mo, mua, nah, nmg, no, nqo, nus, ny, pap, prg, qu, rn, rw, sbp, sh, sma, smi, smj, smn, sms, swc, syr, tk, tl, twq, vai, wa, wo, yav, yi, zgh

## Upgraded `intl-*` Dependencies

The following low-level FormatJS packages have also been upgraded which
provide and take advantaged of the improved CLDR locale data:

* `grunt-extract-cldr-data@2.1.1`
* `intl-messageformat@1.1.0`
* `intl-relativeformat@1.1.0`

## Added `now` Prop to `<FormattedRelative>` Component

`intl-relativeformat@1.1.0` adds support for specifying the "now" value from which relative time is computed. This change adds a new optional prop `now` to the <FormattedRelative> component which will pass along that value to `IntlRelativeFormat#format()` method.

## Added `selectordinal` Support for Messages

`intl-messageformat@1.1.0` adds support for `selectordinal` arguments in messages; e.g.:

```
This is my {num, selectordinal,
    one {#st}
    two {#nd}
    few {#rd}
    other{#th}
} birthday.
```

----

Fixes #78

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
_**Note:** After this is merged it will qualify and a minor version increment_

**Comment by tom76kimo** [comment]
Thanks! Nice work! Looking forward to merge.

**Comment by ericf** [comment]
_Updated description with note on new `selectordinal` support in messages._

**Comment by caridy** [comment]
:8ball:

**Pull request merged**
