### PR TITLE
Upgrade prop-types dep

### PR DESCRIPTION
**Pull request by rattrayalex-stripe**
15.5.4, which this previously relied upon, is marked as having a critical issue: 

> Note: this release has a critical issue and was deprecated. Please update to 15.5.7 or higher.

https://github.com/facebook/prop-types/blob/master/CHANGELOG.md

This upgrades instead to the latest version, which also has a nicer license.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by rattrayalex-stripe** [comment]
Hmm, the cla should be signed now...

**Comment by astorije** [comment]
Related PR: https://github.com/yahoo/react-intl/pull/1057

**Comment by redonkulus** [comment]
Don't think this is necessary since semver will pick up the latest minor version automatically.

**Pull request closed without merging**
