### PR TITLE
Support Short Relative Formats.  Fixes #393

### LINKED ISSUE #393: Short Formatted Relative format
Our designer would like to have the option to have the <FormattedRelative> output shorted versions
e.i 5h ago, 1m ago etc.

How would we go about implementing this? 

Thanks, and great library.

### PR DESCRIPTION
**Pull request by papasmile**
resolve #393

Open up Short Format options on `formatRelative`.  Completes efforts linked from related issue https://github.com/yahoo/react-intl/issues/393

Tests added and updated for short format.

Finally, once merge, related wiki needs to be updated: https://github.com/yahoo/react-intl/wiki/API#formatrelative

### CODE REVIEW

**Comment by aaaaaaamie** [comment]
Hi, what's the eta on getting this merged?

**Comment by aaronbeall** [comment]
@papasmile Does this remove the "best fit" behavior, so you have to explicitly say to format in seconds, minutes, hours, etc?

**Comment by papasmile** [comment]
Hi, @aaronbeall, 'best-fit' is still there via 'style' prop[1].  Units just allows you to override to get units you want.

[1] https://github.com/papasmile/react-intl/blob/master/src/types.js#L92
[2] https://github.com/yahoo/intl-relativeformat#custom-options

**Comment by papasmile** [comment]
@aaronbeall we're just exposing options on Intl Relative Format[1].  Is there a way to get "best fit short unit" with that library that you know of?

[1] https://github.com/yahoo/intl-relativeformat

**Comment by aaronbeall** [comment]
@papasmile Not that I know, that's just what I'm hoping to be able to do. :) +1 for exposing the options. +10 if there was a way to get "best fit short style" which is what I actually need for my project.

**Comment by papasmile** [comment]
np, yea, I don't know that they support that at all.  You could probably log a request/pr to intl-relativeformats for that, though, then bring it back to react-intl as needed.

**Comment by papasmile** [comment]
thanks!

**Pull request merged**
