### PR TITLE
#1047 Hoist non-react statics in injectIntl

### LINKED ISSUE #1047: Please hoist statics in injectIntl
### Expected behavior
statics are hoisted

### Current behavior
statics are not being hoisted
This is breaking stuff for some libraries such as react-navigation, that use:

```
class MyScreen extends React.Component{
    static navigationOptions = {
       [...]
    }
}
````
### Solution

use `hoist-non-react-statics` as described here: https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over

This issue is further described at https://github.com/react-community/react-navigation/issues/332 

An example solution can be viewed here:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/withRouter.js

### PR DESCRIPTION
**Pull request by bringking**
Resolves #1047. We were running into an issue locally using `react-intl` with NextJS, which has a static called `getInitialProps`. This PR adds hoists statics using `hoist-non-react-statics` in the `injectIntl` HOC and adds a test. Thanks for the great library!

### CODE REVIEW

**Comment by bringking** [comment]
I would love to get this landed sometime soon.. is this still maintained?

**Comment by bringking** [comment]
@ericf are you the maintainer? Let me know what I can do to help get this in 🙏

**Comment by bringking** [comment]
Is this library maintained anymore? Anything I can do to help?

**Comment by papasmile** [comment]
@redonkulus is last known committer...

**Comment by redonkulus** [comment]
@okuryu is the most recent maintainer. I have commit access and I merge simple changes, but I'm not an active maintainer. We are definitely looking for more maintainers to continue to move this project along. For any new code changes, it just needs to be properly tested. I've restarted the failing build to see if it was a one off issue.

**Comment by redonkulus** [comment]
As for this PR, the original owner of this library [had a lengthy discussion](https://github.com/yahoo/react-intl/issues/196#issuecomment-173965309) with other folks on why injectIntl does not hoist statics. Its worth reviewing those comments to understand why this was never merged previously.

**Comment by bringking** [comment]
@okuryu @redonkulus @ericf yeah I understand the original discussion and it makes some sense. A library shouldn't concern itself with non-react statics per se. All the problems with HOC's aside, it seems strange to take a stand on this and break expected HOC behavior from many different libs in the ecosystem. Now we have a foot-gun in our repo that we have to handle with a special case.. I disagree with the original authors assertion that it is "brittle". `hoist-non-react-statics` has been in wide use for quite some time. Can we re-visit merging this to be a good citizen with the HOC?

**Comment by papasmile** [comment]
@redonkulus I think you have a volunteer: https://github.com/yahoo/react-intl/issues/1160#issuecomment-412725883

**Comment by redonkulus** [comment]
Thanks for the bump. I'm ok with the change, assuming it won't break anyone if its gets released. @sourabh2k15 has volunteered to help maintain this project too. I'd like to see him review and address any concerns or questions.

**Comment by redonkulus** [comment]
Given the changes and the expectation in the community, I'm ok with merging this.

**Comment by kelly-tock** [comment]
Yes!!!!!!!!

**Comment by sourabh2k15** [comment]
@redonkulus yes I would be contributing more actively from now onwards. I'll help reviewing the other PRs

**Comment by Sparragus** [comment]
I'm very happy this was merged. Thanks @redonkulus for allowing this to go in.

**Comment by backmeupplz** [comment]
soundsgood
v2.4.0 — I have to hoist my non-react statics back to component every time, even with my enormously huge hands. We already live in 2k18, it's a shame that some libraries don't hoist the components — and even when they merge it's just **fake news**. Please, make sure it works. We really need it.

**Comment by Sparragus** [comment]
@backmeupplz Hey. Be more respectful to the maintainers.

**Comment by backmeupplz** [comment]
@Sparragus no offence intended, sorry if I insulted anybody.

**Comment by backmeupplz** [comment]
Also, did `yarn cache clean` and re-installed the `node_modules`. Was testing the theory that this commit was merged to `2.4.0` without the version bump and yarn cached an older version. Didn't work. Will have to investigate further. Manually hoisting the components works.

wiki-background

**Comment by bringking** [comment]
@backmeupplz if I am reading correctly, this wasn't released yet. 2.4.0 was released in Sept. of 2017

**Comment by backmeupplz** [comment]
@bringking oh ok, I'll use `master` branch then :) thx

**Pull request merged**
