### PR TITLE
Bump version to v2.4.0

### PR DESCRIPTION
**Pull request by okuryu**
This includes following changes. ~~Bumping major version depends on the major version up of `intl-messageformat` and `intl-relativeformat`~~.

## Enhancements

* Testing on Node.js v8 instead of v7 (#1024)
* Integrate prettier for code formatting (#1022)
* Support React v16 (#1023)
* Undo (soft) breaking change introduced in 93c0a35 & #816. (#930)
* Template for GitHub Issues (#1017)
* change react-router to react-router-dom-package in react-router-example (#1004)
* Update CLDR to 31 (#1011)
* allow object for description prop (#990)
* Tweak Travis CI (#952)

## Dependencies Updates

* Update yarn.lock file (#1026)
* Bump intl-messageformat version to 2.1.0 (#1005)
* Upgrade intl-messageformat and intl-relativeformat (#986)
* Update rollup-plugin-node-resolve to version 3.0.0 (#948)
* Update rollup-plugin-uglify to version 2.0.0 (#949)
* Update eslint-plugin-react to version 7.0.1 (#945)
* Update cross-env to version 4.0.0 (#914)

### CODE REVIEW

**Comment by redonkulus** [comment]
Does major have to be bumped? Was it bumped in the past when the dependent libraries were updated?

**Comment by redonkulus** [comment]
I'd prefer to not bump major unless there really are API compatible changes.

**Comment by okuryu** [comment]
Either way is okay to me. Regarding https://github.com/yahoo/intl-messageformat/pull/165#issuecomment-313883772, I just thought that there're users who are affected by intl-messageformat's change.

**Comment by okuryu** [comment]
I changed version to v2.4.0.

**Comment by redonkulus** [comment]
Perfect. Thanks!

**Pull request merged**
