### PR TITLE
Prefix Components with "Formatted"

### LINKED ISSUE #60: Number/Date/Mixin components exposed as IntlNumber/IntlDate/IntlMixin
This is a feature request to export the Number/Date/Mixin components as IntlNumber/IntlDate/Mixin.

I love using the ES6 object destructuring syntax, but when I'm consuming react-intl components I cannot use it because it would "hide" the built in Number/Date types. Mixin is slightly different in that there is no conflict -- I just always rename it to IntlMixin to make it a bit more clear about it's use.

I'd love to be able to do the following.

```javascript
var { IntlNumber, IntlDate, IntlMixin } = require('react-intl');
```

Instead of

```javascript
var ReactIntl = require('react-intl'),
  IntlNumber = ReactIntl.Number,
  IntlDate = ReactIntl.Date,
  IntlMixin = ReactIntl.Mixin;
```

And if you end up going this route, I'd probably prefix the other ones with Intl for consistency.

### PR DESCRIPTION
**Pull request by ericf**
This adds "Formatted" as a prefix to all React Intl Components.
See: #65 for discussion

Closes #64
Fixes #60

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by caridy** [comment]
My only issue is with `ReactIntl.IntlMixin`, which seems awkward, where Mixin is not that big of a problem, like it is Number or Date

**Comment by caridy** [comment]
other than that, it LGTM

**Comment by ericf** [comment]
@caridy my thoughts around `IntlMixin` vs. `Mixin` as the export name are that when looking forward it will be common for people to use destructuring and module imports in ES6, and I think that changes how me might want to name our exports.

```js
var {IntlMixin, FormattedNumber} = require('react-intl);
```

```js
import {IntlMixin, FormattedNumber} from 'react-intl';
```

In these two cases it seems preferable to have `IntlMixin` as the name of the prop/export. Otherwise when using ES6 modules you'll want to rename the named export for clarity:

```js
import {Mixin} from 'react-intl';

export default class extends Component {
    mixins: [Mixin], // What is mixin is "Mixin" again?
    render: function () {
        // ...
    }
}
```

Since it won't be clear what the `Mixin` is when looking at the code without referring to the `import` statement, people will probably end up doing:

```js
import {Mixin as IntlMixin} from 'react-intl';
```

So I thought it makes sense to save the need for using `as` and just name the export `IntlMixin` from the start. What do you think? Do you agree when thinking of it this way, or am I being silly :) ?

**Comment by caridy** [comment]
ok, let's roll with IntlMixin

**Pull request merged**
