### PR TITLE
Changed readme and hello-world example to use FormattedMessage to eliminate string fragments

### PR DESCRIPTION
**Pull request by yangsu**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
@yangsu instead of using `<FormattedHTMLMessage>`, this example should use `<FormattedMessage>`: https://github.com/yahoo/react-intl/wiki/Components#formattedmessage

**Comment by yangsu** [comment]
The string contains `<b>` though, that's why i used HTMLMessage

**Comment by ericf** [comment]
The docs I linked to show how to handle that with `<FormattedMessage>`.

**Comment by ericf** [comment]
Thanks!

**Pull request merged**
