### PR TITLE
Port react-router examples to use Create React App

### PR DESCRIPTION
**Pull request by iswanj**
@ericf Here I added CRA for react-router example. Also, Other 3 example ( async, nested, translation ) are little tricky to add CRA, because of the structure of examples. 
So I'll add an another PR for above examples later.
.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
@iswanj I wonder if it's worth using `react-router@4` for this? https://react-router.now.sh

**Comment by iswanj** [comment]
@ericf :) Ok I'll add react-router@4

**Comment by iswanj** [comment]
@ericf Added react-router v4

**Comment by ericf** [comment]
@iswanj Thanks! 🎉

**Pull request merged**
