### PR TITLE
I enhanced the example about react-router

### PR DESCRIPTION
**Pull request by DWboutin**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by ericf** [comment]
Can you please provide a description of what this does?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by DWboutin** [comment]
It only do language change.

**Comment by ericf** [comment]
I'm closing this because it doesn't pass CI, I don't understand what it's adding, and React Router's API has changed.

**Pull request closed without merging**
