### PR TITLE
Template for GitHub Issues

### PR DESCRIPTION
**Pull request by okuryu**
Often the reported issue is not a problem of `react-intl`. It may be a problem with intl.js polyfill or Unicode CLDR. I hope this template should be helpful to author of issues.

### CODE REVIEW

**Comment by okovpashko** [comment]
@okuryu is there any reason not to require a bin with a reproducible example for issues considered as bugs?

**Comment by okuryu** [comment]
if all reporter provide the minimum repro step, I thought that bin isn't necessarily required. It might be a bug on server side. Of course, if we can reproduce with bin, I think that bin is also good.

**Comment by redonkulus** [comment]
@okuryu lerna also has a nice one you get ideas from https://github.com/lerna/lerna/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by okuryu** [comment]
Okay, I upgrade the template based on the good point of lerna. 😎

**Pull request merged**
