### PR TITLE
add react-intl with redux example

### PR DESCRIPTION
**Pull request by Tushant**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by Tushant** [comment]
Sorry i forgot to do that. I signed it now.

Thanks

**Comment by ericf** [comment]
@Tushant would you mind fixing the lint errors?
```
npm run lint:fix
```

**Comment by Tushant** [comment]
Sorry for late response. I was busy on my work. @ericf i get eslint: not found error. When i forked, i did not get .eslintrc file. Do i need to copy that?

Thanks

**Comment by StorytellerCZ** [comment]
Install eslint globally, then it should work.

**Comment by clearlyTHUYDOAN** [comment]
If this doesn't get approved, especially since it's been awhile, I think I'll submit a PR on a redux example once I'm satisfied with my own 🙊  I'll have to sign the cla thing first?

**Comment by okuryu** [comment]
Yes. Please sign the CLA before submit a PR.

**Comment by leonardovillela** [comment]
A Pull request with this example is it still necessary?

**Comment by ashmore11** [comment]
I've implemented this approach but when switching locales, every component that's a child of IntlProvider is being re rendered. How is this avoidable?

**Comment by redonkulus** [comment]
Let’s align on the approach in https://github.com/yahoo/react-intl/pull/1124

**Pull request closed without merging**
